<a href="https://colab.research.google.com/github/EKorchevsky/MachineLearning/blob/main/%D0%9B%D0%B0%D0%B1%D0%BE%D0%BB%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0_%D0%9B%D0%A01_%D0%9A%D0%BE%D1%80%D1%87%D0%B5%D0%B2%D1%81%D1%8C%D0%BA%D0%B8%D0%B9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Корчевський Едуард ФІТ 3-3з Лаболаторна робота 1

In [ ]:
import numpy as np
np.__version__

'2.0.2'

Сторити матрицю 3*3, заповнити цілими випадковими від 1 до 5

In [ ]:
matrix = np.random.randint(1,6, size=(3,3))
matrix

array([[5, 5, 4],
       [4, 1, 4],
       [3, 3, 1]])

Обчислити визначник

In [ ]:
det = np.linalg.det(matrix)
det

np.float64(21.00000000000001)

Знайти добуток всіх елементів матриці

In [ ]:
product = np.prod(matrix)
print("Добуток всіх елементів матриці", product)

Добуток всіх елементів матриці 14400


In [ ]:
prod_1 = np.prod(matrix[0])
prod_2 = np.prod(matrix[1])
prod_3 = np.prod(matrix[2])
prod_1*prod_2*prod_3

np.int64(14400)

Знайти сумму всіх елементів матриці

In [ ]:
sum = np.sum(matrix)
sum

np.int64(30)

Обчислити найбільший та найменший елемент

In [ ]:
max_element = np.max(matrix)
print("Найбільший елемент ",max_element)
min_element = np.min(matrix)
print("Найменший елемент ",min_element)

Найбільший елемент  5
Найменший елемент  1


Знайти середне значення

In [ ]:
mean = np.mean(matrix)
print("Середне значення елементів",mean)

Знайти матрицю що складена за квадратних коренів

In [ ]:
sqrt_matrix = np.sqrt(matrix)
print("Матриця кв. коренів:")
print(sqrt_matrix)

Матриця кв. коренів  [[2.23606798 2.23606798 2.        ]
 [2.         1.         2.        ]
 [1.73205081 1.73205081 1.        ]]


Обчислити сумму елементів кожного рядку

In [ ]:
row_sums = np.sum(matrix, axis=1).reshape(-1,1)
print("Сумма елементів матриці:")
print(row_sums)

Стоврити вектор що містить 25 елементіву. Заповнити числами від 0 до 9. Відсортувати

In [ ]:
vector = np.random.randint(0, 10, size=25)
print("Початковый вектор:",vector)
print("Сортований вектор:",(np.sort(vector)[::-1]))

Початковый вектор: [1 0 5 8 7 4 3 2 5 9 3 6 9 8 1 2 8 0 1 9 4 2 5 3 5]
Сортований вектор: [9 9 9 8 8 8 7 6 5 5 5 5 4 4 3 3 3 2 2 2 1 1 1 0 0]


Знайти моду, медіану, середнє значення, Максимальне і мінімальне.

In [ ]:
from scipy import stats
print("Мода:",stats.mode(vector))

print("Медіана:",np.median(vector))

print("Середнє:",np.mean(vector))

print("Макс:",np.max(vector))
print("Мін:",np.min(vector))

Мода: ModeResult(mode=np.int64(5), count=np.int64(4))
Медіана: 4.0
Середнє: 4.4
Макс: 9
Мін: 0


Створити 2 матриці 4*4 заповниені числами від 1 до 10. обчислити сумму різницю поелементний добуток, частку.

In [ ]:
matrix1 = np.random.randint(1,11, size=(4,4))
matrix2 = np.random.randint(1,11, size=(4,4))
print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)

Матриця 1:
[[ 2  3  7  3]
 [ 4  2  2  2]
 [ 8  4  3  9]
 [ 7 10  5  1]]
Матриця 2:
[[ 5  6  3  9]
 [10  9  7  4]
 [ 3  3  3  2]
 [ 5  5  4  4]]


In [ ]:
print("Сумма:")
print(matrix1 + matrix2)
print("Різниця:")
print(matrix1 - matrix2)
print("Множення:")
print(matrix1 * matrix2)
print("Ділення:")
print(np.divide(matrix1,matrix2, where=2!=0))

Сумма:
[[ 7  9 10 12]
 [14 11  9  6]
 [11  7  6 11]
 [12 15  9  5]]
Різниця:
[[-3 -3  4 -6]
 [-6 -7 -5 -2]
 [ 5  1  0  7]
 [ 2  5  1 -3]]
Множення:
[[10 18 21 27]
 [40 18 14  8]
 [24 12  9 18]
 [35 50 20  4]]
Ділення:
[[0.4        0.5        2.33333333 0.33333333]
 [0.4        0.22222222 0.28571429 0.5       ]
 [2.66666667 1.33333333 1.         4.5       ]
 [1.4        2.         1.25       0.25      ]]


Задати вектор рядок що сітить дійсні числа 1 - 8. Зробити матрицю 3*3. Помножити на вектор рядок, що мітить числа 1-2

In [ ]:
x= np.arange(9.0)
x1 = x.reshape((3,3))
x2 = np.arange(3.0)
print("Добуток")
print(np.multiply(x1,x2))

Добуток
[[ 0.  1.  4.]
 [ 0.  4. 10.]
 [ 0.  7. 16.]]


In [ ]:
x1 = np.arange(6)
np.power(x1,3)
x2=np.array([1,2,3,3,2,1])
x1 ** x2

array([ 0,  1,  8, 27, 16,  5])